### ISSUE TITLE
Fallback for empty translations

### ISSUE THREAD

**Issue by darkcode85** [shioyama/mobility#176] opened 2018-03-03 08:43 UTC
### Context

Right now is impossible to deal with dynamic fallbacks as we have to set the fallback in the model and can not be done dynamically.

### Possible Solution

Would be good to have a new option `fallbacks_for_empty_translations` (not necessarily this name), this is an example of how it could work:

```
class Blog < ActiveRecord::Base
  extend Mobility
  translates :title, type: :string, fallbacks_for_empty_translations: true
end

puts blog.string_translations.inspect
# => [#<Mobility::ActiveRecord::StringTranslation id: 1, locale: "ja", key: "title", value: "モビリティを使う!", translatable_id: 1, translatable_type: "Blog">,
#<Mobility::ActiveRecord::StringTranslation id: 1, locale: "en", key: "title", value: "", translatable_id: 1, translatable_type: "Blog">,
#<Mobility::ActiveRecord::StringTranslation id: 1, locale: "es", key: "title", value: nil, translatable_id: 1, translatable_type: "Blog">]

I18n.locale = :ja
blog.title # => 'モビリティを使う!'

I18n.locale = :en
blog.title # => 'モビリティを使う!'

I18n.locale = :es
blog.title # => 'モビリティを使う!'

# Locale without translation object
I18n.locale = :it
blog.title # => 'モビリティを使う!'
```

I think this will help a lot to deal with empty translations in some scenarios where the default fallback can not be hardcoded.

**Comment by shioyama** [comment] 2018-03-03 10:41
Thanks, if I understand it you want a way to dynamically define fallbacks, e.g. from other model state etc (like user settings) ? That sounds like a pretty common use-case.

My proposal would be to do something like the [Default plugin](http://www.rubydoc.info/gems/mobility/Mobility/Plugins/Default), which allows you to pass a `Proc` as value for the plugin (i.e.. `translates :title, default: lambda { ... }`). The proc is evaluated in the context of the model instance, and it can optionally accept up to three arguments: the attribute name, the locale, and the options passed to the accessor.

So in this case, the interface would be:

```ruby
class Blog < ActiveRecord::Base
  extend Mobility
  translates :title, fallbacks: lambda { |attribute, locale| ... }
end
```

In the lambda you could fetch the blog's settings and find the fallback for the current locale (`locale` above).

That said, I don't really understand your example. You are not defining anything dynamic to define the fallbacks, so where is your blog model fetching the fallback locale from the settings?

In Globalize, by the way, `fallbacks_for_empty_locales` is used to specify that you want to fallback when the locale is blank (nil or empty string). I don't see anything about dynamically defining fallbacks.

**Comment by shioyama** [comment] 2018-03-03 10:47
Or maybe I'm misunderstanding and this is a duplicate of #161 ? You can pass `fallbacks: true` in Mobility and it will default to using a new instance of `I18n::Locale::Fallbacks`, but this is not the same as `I18n.fallbacks`.

**Comment by darkcode85** [comment] 2018-03-03 15:14
Thanks @shioyama, I will explain my scenario in detail so you can understand my situation:

I have a `Site` model that has a `has_many :languages` relationship with the `Language` model, the owner of the site can create has many languages and assign the default language to any of them. If they set up multiple languages then when they create a blog I have a multi language form where the title, content, etc.. can be fill out in the available languages, but what normally happen is that the owners only fill out the content for the default language, so if you visit the blog on a locale without translation then it show a blank content, the business logic here is to show the content for the default language if the translations are blank.

So for that reason I have tried to add dynamic fallbacks because for example for the site 1 the fallback hash could be `fallbacks: { es: :en, ... }` and for the site 2 the fallbacks could be different `fallbacks: { en: :ja, ... }` depending to the default language used. I tried to do that using Mobility and I didn't have success, I also tried the `fallbacks: true` but it doesn't work in this scenario.

What I had in other app in a similar scenario (using globalize) was the `fallbacks_for_empty_translations: true` option which fixed this scenario. 

I also tried the default plugin but again looks like I can not pass dynamic content, ej: `default: lambda { |attribute, locale| self.title_"#{default_language_locale}" }`

So I'm not sure if fix this problem is possible in Mobility but if not I propuse to add the `fallbacks_for_empty_translations: true` option to just use the default content instead of pass dynamic hashes in the model context (will not be something good to add it on all the models).

Another possible solution would be to globally set the fallbacks in the controller context instead to have to add it in each model, so for example in the `application_controller.rb` we can have a `before_action` to set the fallback hash depending in the site configuration and that will work globally for all the models.

Hope this explanations make sense and you can now understand much better the problem and see if Mobility already has a solution for this scenario or maybe add one of the possible solution (or a new one).

**Comment by darkcode85** [comment] 2018-03-04 06:00
After review #161 in more detail looks like this is a possible duplicate, because what I want could be achievable setting a dynamic `I18n.fallbacks` in the `application_controller.rb` based in the default language selected but the issue is that setting `fallbacks: true` is not respecting the `I18n.fallbacks`

**Comment by shioyama** [comment] 2018-03-04 08:51
Yes I believe this is a duplicate. Thanks for posting, let's move discussion to #161.

**Closed by shioyama** 2018-03-04 08:51 UTC
Labels: fallbacks_plugin

**Comment by francescobbo** [comment] 2022-04-27 16:11
Hi @shioyama, sorry for bumping up an old discussion. Was this ever implemented? If not, can you recommend alternatives for dynamic/stateful fallbacks?

Many thanks for Mobility btw!

> Thanks, if I understand it you want a way to dynamically define fallbacks, e.g. from other model state etc (like user settings) ? That sounds like a pretty common use-case.
> 
> My proposal would be to do something like the [Default plugin](http://www.rubydoc.info/gems/mobility/Mobility/Plugins/Default), which allows you to pass a `Proc` as value for the plugin (i.e.. `translates :title, default: lambda { ... }`). The proc is evaluated in the context of the model instance, and it can optionally accept up to three arguments: the attribute name, the locale, and the options passed to the accessor.
> 
> So in this case, the interface would be:
> 
> ```ruby
> class Blog < ActiveRecord::Base
>   extend Mobility
>   translates :title, fallbacks: lambda { |attribute, locale| ... }
> end
> ```
> 
> In the lambda you could fetch the blog's settings and find the fallback for the current locale (`locale` above).
