### ISSUE TITLE
Duplicate ancestors resulting in always-failing queries

### ISSUE THREAD

**Issue by spencerwp** [shioyama/mobility#507] opened 2021-02-16 19:36 UTC
In all latest versions of mobility I have tried, there is an issue specifically regarding the decorator pattern I am using where multiple Mobility::Translation classes end up in the model's class ancestors, both being added to the query predicates, resulting in always-fail conditions.

## Context

I am using the :table backend with active record in a rails project.

The example decorator pattern is as-follows

app/models/post.rb
```
class Post < ApplicationRecord
end
```

app/decorators/post_decorator.rb
```
module PostDecorator
  def self.prepended(base)
    base.extend Mobility
    base.translates :title
    base.class_eval do
      default_scope { i18n }
    end
  end
end

::Post.prepend(PostDecorator)
```

config/application.rb
```
...
class Application < Rails::Application
    config.to_prepare do
      Dir.glob(File.join(File.dirname(__FILE__), "../app/**/*_decorator*.rb")) do |c|
         Rails.configuration.cache_classes ? require(c) : load(c)
      end
    end
...
```

Resulting in an ancestor list of

```
[PostDecorator, Post(id: integer, title: string, created_at: datetime, updated_at: datetime), 
#<Translations (Mobility::Backends::ActiveRecord::Table) @names=title>, 
Mobility::Plugins::ActiveModel::Dirty::InstanceMethods, 
Post::MobilityArTableTranslations, 
#<Translations (Mobility::Backends::ActiveRecord::Table) @names=title>, 
Mobility::Plugins::AttributeMethods::InstanceMethods, 
Mobility::Plugins::ActiveRecord::Dirty::InstanceMethods, 
Mobility::Plugins::ActiveRecord::Dirty::HandlerMethods, 
Mobility::Plugins::Backend::InstanceMethods, 
Post::GeneratedAssociationMethods, 
Post::GeneratedAttributeMethods, 
ApplicationRecord(abstract), 
ApplicationRecord::GeneratedAssociationMethods, 
ApplicationRecord::GeneratedAttributeMethods, 
ActiveRecord::Base,
......]
```

## Expected Behavior
```
Post.find_by(title: "en_title")
   (0.6ms)  SELECT sqlite_version(*)
  Post Load (0.2ms)  SELECT "posts".* FROM "posts" INNER JOIN "post_translations" "post_translations_en" ON "post_translations_en"."post_id" = "posts"."id" AND "post_translations_en"."locale" = 'en' WHERE "post_translations_en"."title" = 'en_title' LIMIT ?  [["LIMIT", 1]]
 => #<Post ... >
```

## Actual Behavior
```
Post.find_by(title: "en_title")
   (0.6ms)  SELECT sqlite_version(*)
  Post Load (0.2ms)  SELECT "posts".* FROM "posts" INNER JOIN "post_translations" "post_translations_en" ON "post_translations_en"."post_id" = "posts"."id" AND "post_translations_en"."locale" = 'en' WHERE "post_translations_en"."title" = 'en_title' AND "post_translations_en"."title" IS NULL LIMIT ?  [["LIMIT", 1]]
 => nil
```

## Possible Fix

This seems likely related to ruby in general, but more testing is necessary, see https://bugs.ruby-lang.org/issues/8066

I have tracked this down to the following snippet from the active_record plugin's query.rb - where multiple Mobility::Translation ancestors exist in the model's class after being decorated.

https://github.com/shioyama/mobility/blob/master/lib/mobility/plugins/active_record/query.rb#L240

```
def translation_modules(scope)
    scope.model.ancestors.grep(::Mobility::Translations)
end
```

I do not think there is ever a case where multiple translations classes are included in the same class, but I could be wrong about that.

My quick workaround is to return only the first Mobility::Translations ancestor (which is good enough for me).

**Comment by shioyama** [comment] 2021-02-18 13:11
Thanks for the report!

> I do not think there is ever a case where multiple translations classes are included in the same class, but I could be wrong about that.

Yes indeed, this is by design. If you call `translates` multiple times it will include multiple modules. This is so that you can configure different attributes to use different backends, etc.

That said, the query plugin could be made to handle this situation, although I hesitate because normally you shouldn't really be calling `translates` with the same attribute multiple times on a single class...

**Comment by spencerwp** [comment] 2021-02-18 16:50
Thank you for the explanation.  This makes a lot more sense now, especially as the opts values are deleted as they are looped through.  I will do some more definitive testing to see if this is being caused by ruby itself or `translates` is actually being called multiple times.

My workaround is now modified to handle the case of multiple backends by getting unique Mobility::Translations classes for each `names` attribute.  Since in fact `translates` should not ever be called multiple times on the same attribute (especially not with different backends), for the specific scope we're in at the time, this should work fine.

`Post.ancestors.grep(Mobility::Translations).uniq{|c| c.names}`

Maybe too hacky to include in the project, but I will also try to find an external alternative.  This seems appropriate for now and should not introduce any issues.

**Comment by shioyama** [comment] 2021-02-20 06:49
I just tested this in a dummy app and the problem is not to do with Mobility but with your `PostDecorator` and how it is loaded. The block in `application.rb` is using `load` if caches aren't cached (which is the default in dev mode), which means if `to_prepare` is called multiple times it will _re-load_ the `PostDecorator` and prepend it _twice_ to `Post`. This is why you end up with two `Mobility::Translations` classes in the ancestors chain (I actually managed to get three of them at one point, depending on how you trigger reloads).

If you remove that `to_prepare` stuff and in a console just load the decorator with `PostDecorator` and _then_ check the ancestors, you should see there is just one, as expected, and everything works fine.

I'm not really familiar with the decorator pattern nor with that `to_prepare` code but it seems to me the `prepended` block is not a good way to set things up because it will get triggered multiple times even if the `PostDecorator` has already previously been prepended.

One quick fix would be to only prepend if the module has not already been prepended:

```ruby
::Post.prepend(PostDecorator) unless ::Post.included_modules.include?(PostDecorator)
```

This fixes the problem for me.

In any case, I'm going to close this since it's not really a Mobility problem.

**Closed by shioyama** 2021-02-20 06:49 UTC
Labels: active_record, compatibility

**Comment by shioyama** [comment] 2021-02-20 06:51
> which should handle cases of multi-backend on individual model attributes and have the ancestor list respond in the expected way.

This shouldn't be necessary if Mobility is used as expected, and `translates` is not called multiple times with the same attribute(s).
