### ISSUE TITLE
Performance much slower in version 1.2.3

### ISSUE THREAD

**Issue by f1sherman** [shioyama/mobility#544] opened 2021-11-09 21:59 UTC
Performance appears to be much slower in version 1.2.3 than version 1.2.1

## Context
I haven't been able to track this down completely but I believe the performance issue is related to [this PR](https://github.com/shioyama/mobility/pull/531) as I can't reproduce it on version 1.2.1 and we make extensive use of fallbacks.

I've tried to reproduce this with a vanilla Rails app and haven't been able to get but wanted to get this over to you in case you had any ideas.

Holding everything else constant, just initializing an ActiveRecord instance that has translated attributes is orders of magnitude slower.

Version 1.2.3:

```
Benchmark.realtime { 1000.times { Thing.new.title } }

=> 85.30171160000464
```

Version 1.2.1:

```
Benchmark.realtime { 1000.times { Thing.new.title } }

=> 0.3301175000015064
```

## Expected Behavior
Performance is not significantly worse in version 1.2.3 than 1.2.1

## Actual Behavior
Performance is significantly worse in version 1.2.3 than 1.2.1

## Possible Fix

Revert https://github.com/shioyama/mobility/pull/531

**Comment by shioyama** [comment] 2021-11-17 12:51
Hmm that's strange... the intention was to make it faster. I can revert but let me see if anything stands out. :eyes:

**Comment by shioyama** [comment] 2021-11-17 13:16
Ok I see the issue, I think #546 should fix it but I haven't benchmarked it. Could you have a look?

**Comment by f1sherman** [comment] 2021-11-17 18:02
@shioyama thank you! I tried that branch and I get an error when running my benchmark. Stack trace is below:

```
Exception: NoMethodError: undefined method `[]' for nil:NilClass
--
0: vendor/bundle/ruby/3.0.0/bundler/gems/mobility-15be6e8c2950/lib/mobility/backends/active_record/pg_hash.rb:19:in `read'
1: vendor/bundle/ruby/3.0.0/bundler/gems/mobility-15be6e8c2950/lib/mobility/plugins/active_record/query.rb:64:in `read'
2: vendor/bundle/ruby/3.0.0/bundler/gems/mobility-15be6e8c2950/lib/mobility/plugins/cache.rb:69:in `read'
3: vendor/bundle/ruby/3.0.0/bundler/gems/mobility-15be6e8c2950/lib/mobility/plugins/fallbacks.rb:156:in `block in read'
4: vendor/bundle/ruby/3.0.0/bundler/gems/mobility-15be6e8c2950/lib/mobility/plugins/fallbacks.rb:155:in `each'
```

**Comment by shioyama** [comment] 2021-11-21 11:47
@f1sherman Hmm... the tests here pass, so I'm a bit confused what's going on there. That error doesn't happen with 1.2.3 or `master` branch?

**Comment by shioyama** [comment] 2021-11-21 12:04
@f1sherman It seems from that trace that the `translations` hash on the column is `nil`. The default value should be `{}`. Are you sure the column data on the model is correct? Seems to me the problem is not related to the change here.

**Comment by f1sherman** [comment] 2021-11-21 14:48
@shioyama I'm running the same benchmark that I did originally, which is just calling a translated attribute on a brand new record (see below). It does not raise an error on 1.2.1 or 1.2.3, I haven't tried `master` yet but can do that if you'd like.

```
Benchmark.realtime { 1000.times { Thing.new.title } }
```

**Comment by shioyama** [comment] 2021-11-21 22:17
What is the setup though? What is "Thing"?

The error is because the json translations column is null. I don't see the relationship with fallbacks.


On November 21, 2021 11:48:38 PM GMT+09:00, Brian John ***@***.***> wrote:
***@***.*** I'm running the same benchmark that I did originally, which

**Comment by f1sherman** [comment] 2021-11-21 22:23
@shioyama `Thing` is just an ActiveRecord model with a translated `title` attribute. I'm sorry I'm not very familiar with the underlying libraries involved, so it's tough for me to give more information without investing quite a bit of time. I'll see if I can find time in the next few weeks to dig in further. Otherwise if there is anything else that I can do to help give you more information please let me know. Thanks so much for your help on this!

**Comment by shioyama** [comment] 2021-11-23 05:41
Hi @f1sherman 

So the problem is that you (helpfully) pointed out the perf regression, which #546 should fix. All tests pass. But if you tell me that you get an error, I want to respond to that, but I can't do anything with the info you've provided.

e.g. what backend are you using? (from the trace it looks like json/jsonb/hstore) What else is in the `Thing` class?

Basically, anything that you can do to help me reproduce the issue would be helpful, because it's not at all obvious from the code changes why you would get that error. As I mentioned, the trace makes it look like `translations` is `nil`, which is nothing to do with fallbacks.

I'm a bit stuck for what to do without more info. If you can provide steps to reproduce that would be ideal

**Comment by shioyama** [comment] 2021-11-23 05:51
I just created a fresh Rails 6.1 app with a model with a jsonb column with the jsonb backend, with this branch, and had no issues setting/getting attributes, saving, and falling back.

The error in your trace makes me think your db did not set a default value for the column, like this (for a model `Post` with attribute `title`):

```
    create_table :posts do |t|
      t.jsonb :title, default: {}

      t.timestamps
    end
```

If you don't set the default value then I would expect that you would get the error you reported. This is the same for any version of Mobility, and is [documented in the wiki](https://github.com/shioyama/mobility/wiki/Postgres-Backends-%28Column-Attribute%29#railsactiverecord).

Since I can't see any issues here, I'm going to release the PR, but I'd really like to be sure the issue isn't a real one. Can you confirm the database is not missing a default value? And please try the same benchmark (with the same data/db) on other versions of Mobility?

**Comment by f1sherman** [comment] 2021-11-23 13:25
@shioyama sorry for not providing more info and putting you in a tough spot. The `title` attribute is a `jsonb` column and it is missing a default of `{}`, like you guessed. I'm not sure why I wasn't getting the same error on the previous version of the code with the same benchmark but that at least gives me a good lead on how to fix it on our side. The only other suggestion I'd offer for your consideration is reverting [the change that introduced the issue](https://github.com/shioyama/mobility/pull/531), since it appears that it was a refactor/code clean-up rather than introducing critical functionality, but I can certainly understand why you wouldn't want to do that since #546 fixes the issue as long as defaults are set properly.

I'll find some time in the coming weeks to fix the default on that column, pull down the latest version of `mobility`, and let you know if I see any further issues.

Thanks again for your help and quick attention to this!

**Comment by shioyama** [comment] 2021-11-27 04:00
> I'm not sure why I wasn't getting the same error on the previous version of the code with the same benchmark but that at least gives me a good lead on how to fix it on our side.

Hmm this is strange for sure. It seems like the previous fallbacks code was perhaps supplying that default version somehow, although I don't really see how :thinking: 

> The only other suggestion I'd offer for your consideration is reverting the change that introduced the issue

Yes but this just leaves us at a standstill: we can't make the change now because there _might_ be an issue. I'd prefer to figure out why the updated code doesn't work.

I'm going to see if I can reproduce the phenomenon, but otherwise I'm just going to ship #546.

**Comment by shioyama** [comment] 2021-11-27 04:12
Ok I can reproduce this :tada: 

I'll try to figure out what's going on.

**Comment by shioyama** [comment] 2021-11-27 04:22
Ok sorry, the issue has nothing to do with fallbacks or the change. It's related to https://github.com/shioyama/mobility/pull/536 which is on the master branch.

I'll just rebased the change in #546 onto the `1-2` branch and ship it there, should be no issues.

The problem you're seeing on `master` is because of the fix for this issue: https://github.com/shioyama/mobility/issues/535

And basically the solution is, yes, to set a default value for the jsonb column! But it will be released in 1.3 not a patch version, with a warning about it.

So this is all clear now, sorry @f1sherman I should have realized this.

**Comment by f1sherman** [comment] 2021-11-27 15:58
No worries at all, so glad you tracked this down! Thank you @shioyama!

**Closed** 2021-11-28 04:54 UTC
Labels: bug

**Comment by shioyama** [comment] 2021-11-28 04:55
@f1sherman I released [1.2.4](https://rubygems.org/gems/mobility/versions/1.2.4), when you have a chance can you check that the regression is fixed for you?

**Comment by f1sherman** [comment] 2021-11-28 13:37
Absolutely! I will give it a try and report back.

**Comment by f1sherman** [comment] 2021-12-07 20:03
@shioyama just confirming that performance looks much better now, thank you!

Before:

```
Benchmark.realtime { 1000.times { Thing.new.title } }

=> 85.30171160000464
```

After:

```
Benchmark.realtime { 1000.times { Thing.new.title } }

=> 0.6135440160287544
```
