### ISSUE TITLE
Order does not work on jsonb backend

### ISSUE THREAD

**Issue by SxDx** [shioyama/mobility#341] opened 2019-10-07 09:29 UTC
## Context
model.rb

id | name
------------ | -------------
1 | {"de": "Te", "en": "Da"}
2 | {"de": "Do", "en": "Do"}

model_controller.rb
```ruby
I18n.locale = :en
SomeModel.all.order(name: :asc)
```

## Expected Behavior
Order should be 1,2 because "Da" < "Do"

## Actual Behavior
Order is acutally 2,1 because I think its is comparing the whole jsonb string and the first 
non-equal character pair is "T" and "D"
Further the sortings seems to be case-sensitive, resulting in names starting with lowercase characters coming at the end.

**Comment by shioyama** [comment] 2019-10-07 10:31
You need the `i18n` scope, otherwise indeed you are ordering on the json value itself.

So try this:

```ruby
SomeModel.i18n.order(name: :asc)
```

All backends are tested thoroughly, I'd be very surprised if this didn't work.

**Comment by SxDx** [comment] 2019-10-07 11:19
Yes you are correct, I missed that i need the `i18n` scope for ordering too.

Sorting is still case-sensitive, is there a way to specify case-insensitive sort?

**Comment by shioyama** [comment] 2019-10-07 12:40
> Yes you are correct, I missed that i need the i18n scope for ordering too.

You can make `i18n` the default scope if you want to always apply it.

> Sorting is still case-sensitive, is there a way to specify case-insensitive sort?

No, but ordering on a normal text column would also be case-sensitive by default, right? I don't see why you would expect it to be any different in this case.

**Comment by shioyama** [comment] 2019-10-07 13:00
I'd like to close this, since it's not a bug. However, thinking about this, I realized it would be nice if you could use the block-format on `order`, `pluck` etc so you could do this:

```ruby
Post.i18n.order { title.lower }
```
and it would order on downcased `title`. Currently the block form only works for `where` (and `where.not`), so you *can* do this:

```ruby
Post.i18n { title.lower.eq('foo') }
```

**Comment by shioyama** [comment] 2019-10-08 03:46
I'm closing this, if you feel a feature for case insensitive order makes sense, feel free to re-open as a feature request.

**Closed by shioyama** 2019-10-08 03:46 UTC
