### ISSUE TITLE
Avoid using scope i18n

### ISSUE THREAD

**Issue by shadowed87** [shioyama/mobility#6] opened 2017-03-15 19:24 UTC
Is it a way to use the i18n scope by default in every model that includes mobility?

Model.where(name: 'abc')

instead of 

Model.i18n.where(name: 'abc')

**Comment by shioyama** [comment] 2017-03-15 22:51
Yes I figured this request would come up. The problem is that this would "pollute" the space of normal scopes with overrides for translated attributes. In working on Globalize, there were people who did not like this, and I can understand why.

I think we can make this an option that is disabled by default. I'll look into it.

**Comment by shadowed87** [comment] 2017-03-16 00:09
I see now the problem, makes sense.

Temporarly, I'm using a default scope when using mobility
 
```
translates :name, fallbacks: true
 default_scope { i18n }
```

**Comment by shioyama** [comment] 2017-03-16 13:49
Actually, I think `default_scope { i18n }` is a great solution to this problem. I'm closing this, if there's something that you need for this which `default_scope` does not handle, feel free to re-open.

**Closed by shioyama** 2017-03-16 13:49 UTC
Labels: feature
