### ISSUE TITLE
Severe memory leaks

### ISSUE THREAD

**Issue by ingemar** [shioyama/mobility#167] opened 2018-02-07 12:30 UTC
I'm experiencing severe memory leaks after deploy since Mobility was introduced to the project. 

Removing Mobility mitigates the issue. Any ideas where to look?

**Comment by shioyama** [comment] 2018-02-07 12:42
Wow, ok that's not good -- first I've heard of memory leaks.

Some quick questions:
- what version of Mobility are you using?
- what backend?
- what plugins? (i.e. dirty, locale_accessors, etc.)
- anything else special you're doing?

Also, assuming you're using the latest (0.4.2), could you try downgrading to say 0.3.x etc and see if anything changes?

I consider this a really urgent issue to fix. If it's easier we could move discussion to [gitter](https://gitter.im/mobility-ruby/mobility).

**Comment by shioyama** [comment] 2018-02-07 12:45
[This](https://github.com/shioyama/mobility/blob/a52998479893e33a6df5bfd395f50f76884cf64e/spec/mobility/backends/active_record/key_value_spec.rb#L411-L418) is the only time I've really seen (and avoided) a memory leak in Mobility so far. But I could imagine something like this creeping up in one of the places where anonymous modules are included since they never get garbage-collected (usually there should be just a few).

**Comment by shioyama** [comment] 2018-02-07 12:58
Considering the above, do you use querying? i.e. `Post.i18n.where(...)` type things. This is the only place up to now where I've seriously considered the possibility of memory leaks.

**Comment by ingemar** [comment] 2018-02-07 15:54
what version of Mobility are you using?
`0.3.3`

what backend?
ActiveRecord with KeyValue 

what plugins? (i.e. dirty, locale_accessors, etc.)
```ruby
[1] pry(main)> Mobility.config.plugins
=> [:cache, :dirty, :locale_publish, :fallbacks, :publishable_locale_with_fallback, :presence, :default, :attribute_methods, :fallthrough_accessors, :locale_accessors]
```

anything else special you're doing?
Hmm not really.

**Comment by shioyama** [comment] 2018-02-07 21:56
```ruby
=> [:cache, :dirty, :locale_publish, :fallbacks, :publishable_locale_with_fallback, :presence, :default, :attribute_methods, :fallthrough_accessors, :locale_accessors]
```

Hmm... ok, well `locale_publish` and `publishable_locale_with_fallback` are not standard. Have you custom defined some plugins for your application?

**Comment by shioyama** [comment] 2018-02-09 00:43
@ingemar I can't reproduce these leaks, so unless you can provide details on your setup, I'm going to have to close this. In particular those two plugins make me a bit suspicious. But also, I haven't heard about memory leaks from anyone else, and there are companies using Mobility in production, so I would have expected to have heard about this earlier.

**Comment by shioyama** [comment] 2018-02-09 00:50
Just as a very minimal test:

```ruby
GC.start
ObjectSpace.count_objects({})[:TOTAL]
#=> 302848

**Comment by shioyama** [comment] 2018-02-09 01:45
Here's a quick test. I created a Gemfile with just Mobility and ActiveRecord:

```ruby
source 'https://rubygems.org'

gem 'mobility', '0.3.3'
gem 'activerecord'
```

Now in irb, check object counts after garbage cleaning, to see what Mobility is adding after ActiveRecord is included:

```ruby
GC.start
obj_count = ObjectSpace.count_objects({}); obj_count[:TOTAL] - obj_count[:FREE]
#=> 46298
require "active_record"
GC.start
obj_count = ObjectSpace.count_objects({}); obj_count[:TOTAL] - obj_count[:FREE]
#=> 74917
```

So ActiveRecord is creating `74917 - 46297` or 28,620 objects that are not garbage-cleaned (mostly frozen strings).

Now we can check how much Mobility (v0.3.3) is adding to that:

```ruby
require "mobility"
obj_count = ObjectSpace.count_objects({}); obj_count[:TOTAL] - obj_count[:FREE]
#=> 76625
```

So off the bat, Mobility is adding `76625 - 74917` or 1708 objects. That's actualy more than I would expect, but percentage wise it's about 6% of ActiveRecord... so not out of whack.

That's just a sanity check that without even using Mobility, it's not adding crazy amounts of un-deallocatable objects; it's adding around 1700 objects when you include it, mostly strings, etc.

Now what happens if we actually use it. This is a different project now with a `Post` model. Start by checking the total # of objects in a rails console:

```ruby
GC.start
obj_count = ObjectSpace.count_objects({}); obj_count[:TOTAL] - obj_count[:FREE]
#=> 204996
```

Now do something with Mobility:

````ruby
1000.times.with_index { |i| Post.new(title: "foo#{i}", author: "bar#{i}", content: "baz#{i}").save; Post.i18n.find_by(title: "foo#{i}") }
```

and check the number of un-deallocatable objects:

```ruby
GC.start
obj_count = ObjectSpace.count_objects({}); obj_count[:TOTAL] - obj_count[:FREE]
#=> 216113
```

so we've increased this number by `216113 - 204996` or 11,117 objects.

I suspect a lot of this is related to initialization/caching, however, which you can check if you run the same thing above again (another 1000 times), then run `GC.start` to clean unused objects, and check the count again. I did this and I get 216118, or a total increase of *5 objects* that cannot be de-allocated. This is not zero, but given that I'm running this stuff in a console that is keeping a history, I consider this a likely error bar on this calculation.

So I can't see any obvious leak. I'm closing this although I'm ready to dig deeper if you can provide a reproducible example where this happens. I take this problem really seriously so if it's really happening I want to find out why and fix it asap.

**Closed by shioyama** 2018-02-09 01:45 UTC
Labels: bug

**Comment by ingemar** [comment] 2018-02-09 20:51
Thanks!

**Comment by shioyama** [comment] 2018-02-10 02:25
Please do let me know though if the problem persists and if you can provide more info on your setup :smile:
