### ISSUE TITLE
not working well with ancestry gem 

### ISSUE THREAD

**Issue by kevin-jj** [shioyama/mobility#31] opened 2017-05-18 00:01 UTC
The required column of ancestry that records the hierarchy will be null after loading all of categories.  I can not figure out the reason.

any idea? Thanks.

@shioyama

**Comment by shioyama** [comment] 2017-05-18 08:21
Sorry I really don't know the ancestry gem at all. Can you describe what you did and what it is supposed to do?

Anything that tries to use a translated attribute as a column will break, because it is not a column (it is a virtual attribute). So fixing the problem may be difficult, depending on the implementation.

**Comment by kevin-jj** [comment] 2017-05-18 12:21
https://github.com/stefankroes/ancestry

**Comment by shioyama** [comment] 2017-05-18 13:04
Hmm ok that might be Mobility conflicting with something in Ancestry. I'll have a look.

**Comment by shioyama** [comment] 2017-06-22 02:17
So I've created a test app with Mobility (0.1.18) and Ancestry (3.0.0) and I see no conflict.

```ruby
category1 = Category.new
category1.name = "foo"
category1.save

category2 = Category.new
category2.parent = category1
category2.save

Category.last.parent
#=> #<Category id: 1, created_at: "2017-06-22 02:08:17", updated_at: "2017-06-22 02:08:17", ancestry: nil>
Category.first.children
#=> #<ActiveRecord::Relation [#<Category id: 2, created_at: "2017-06-22 02:08:41", updated_at: "2017-06-22 02:08:41", ancestry: "1">]>                                                       
```

I don't see any issue here. I'm closing this. Please show a reproducible bug (i.e. failing test or gist with code example) if you want me to investigate further.

**Closed by shioyama** 2017-06-22 02:17 UTC
Labels: active_record, compatibility
