### ISSUE TITLE
"New" configuration style breaks factory bot instances in tests

### ISSUE THREAD

**Issue by eiapopeia** [shioyama/mobility#251] opened 2018-06-07 08:07 UTC
## Context
I use FactoryBot and Mobilty in an Rails 5.2 project. When Upgrading to new version a new Mobility configuration style is needed.  This is my configuration:
``` ruby
Mobility.configure do |config|
  config.default_backend = :table
  config.accessor_method = :translates
  config.query_method    = :i18n
  # for old Version (Mobility 0.6.0 with deprecation warning)
  config.default_options = { locale_accessors: true } # deprecated
  # following line in new version (0.7.x) needed but doesn not work in old version either
  config.default_options[:locale_accessors] = true
end
```
This is my Model:
```ruby
class SectionDatum < ApplicationRecord
  extend Mobility
  translates :name,
             type: :string,
             fallbacks: { en: :de }
```
I use minitest and FactoryBot gem. 
This is the factory for The section datum class:
``` ruby
FactoryBot.define do
  factory :section_datum do
    sequence(:name) { |n| "SectionDAtum #{n}" }
    # […]
  end
end
```

## Expected Behavior
I had a test that worked with old syntax of configuration:
``` ruby
test 'should set german name' do
    original_section_datum = create(:section_datum)
    original_section_datum.name_de = 'some_name'
    assert_equal 'some_name', original_section_datum.name_de
end
```

## Actual Behavior
With the new syntax, this does not pass. Neither with old nor the new version of the gem.
```
Minitest::Assertion: Expected: "some_name"
  Actual: nil
```

**Comment by shioyama** [comment] 2018-06-07 12:20
I'm not really sure what's going on, but the issue would have to be with configuration options that you were *unsetting* with the old configuration syntax.

When you set:

```ruby
config.default_options = { locale_accessors: true }
```

You're also setting all other plugin options to `nil`. The new syntax only sets each option separately, so you don't unset the others unintentionally.

So I suppose perhaps this would "fix" the issue:

```ruby
config.default_options[:locale_accessors] = true
config.default_options[:cache] = false
config.default_options[:presence] = false
config.default_options[:presence] = nil
```

This "unsets" everything the way you had previously, although I don't understand why this should be necessary. If this *does* fix the issue, I'd like to know why you need those plugins disabled in your spec for it to pass...

**Comment by eiapopeia** [comment] 2018-06-07 13:35
Disabling the Cache does fix the test indeed. Hmm, I think it is not so good to disable caching?

**Comment by shioyama** [comment] 2018-06-07 13:45
It's not very good, no. I'd like to understand why it's necessary to get that spec to pass...

**Comment by shioyama** [comment] 2018-06-07 13:48
Hmm actually, what you actually had previously was all nils, so more like this:

```ruby
config.default_options[:locale_accessors] = true
config.default_options[:cache] = nil
config.default_options[:presence] = nil
config.default_options[:default] = nil
```

`nil` for the cache will actually still enable it. Can you try this config and see if it passes?

**Comment by shioyama** [comment] 2018-06-07 13:50
Or you can also do this:

```ruby
config.default_options.clear
config.default_options[:locale_accessors] = true
```

This should have the same effect as assigning a hash to `default_options` like you did in earlier versions.

**Comment by shioyama** [comment] 2018-06-08 01:36
@eiapopeia If you can provide a test app or test case demonstrating this issue, I can help. Otherwise there's not really anything I can do for this.

**Comment by eiapopeia** [comment] 2018-06-08 08:46
@shioyama I will try to create a basic app to reproduce the error.

**Comment by shioyama** [comment] 2018-06-08 12:34
Thanks for updating!

> Also i noticed that setting a translation to '' (empty string) now returns nil at the getter. This was returning an empty string before.

That's because of `presence`, which is a plugin which basically eliminates blank strings. You were previously turning it off, but now it is on.

I'll close this issue, glad to hear it's not a bug :smile:

**Closed by shioyama** 2018-06-08 12:34 UTC
Labels: active_record, bug, compatibility
