### ISSUE TITLE
Two languages are the fallback of each other

### ISSUE THREAD

**Issue by enthusiasmus** [shioyama/mobility#262] opened 2018-08-28 09:56 UTC
## Issue 

We have a class `SiteLink` which owns a attribute `label`. We have two lanuages `de` and `fr`. The fallback of `de` is `fr` and the fallback of `fr` is `de`. But when the locale is set to `fr` mobility returns the `de` value, instead of the existing `fr` value.

## Example
```
class SiteLink < ApplicationRecord
  extend Mobility
  translates :label, locale_accessors: [:de, :fr], fallbacks: { :de => :fr, :fr => :de }
end
```

```
[18] pry(main)> I18n.locale = :de
=> :de
[19] pry(main)> site_link = SiteLink.new
=> #<SiteLink:0x0055597032ca70 id: nil, label: {}>
[20] pry(main)> site_link.label = "Event"
=> "Event"
[21] pry(main)> I18n.locale = :fr
=> :fr
[22] pry(main)> site_link.label = "événement"
=> "événement"
[23] pry(main)> site_link.label
=> "Event"
[24] pry(main)> site_link.label_fr
=> "événement"
[25] pry(main)> site_link
=> #<SiteLink:0x0055597032ca70 id: nil, label: {"de"=>"Event", "fr"=>"événement"}>
```
The output of line 23 is incorrect. The output should be `événement`.

## Context
MySQL 5.7.22, Active Record, Mobility 0.7.6

Any ideas? Best regards - Lukas

**Comment by shioyama** [comment] 2018-08-28 13:09
I'm not able to reproduce this. Here's what I see:


```ruby
class Question < ApplicationRecord
  translates :text, locale_accessors: [:de, :fr], fallbacks: { de: :fr, fr: :de }
end
```

```ruby
Loading development environment (Rails 5.2.0)
irb(main):001:0> I18n.locale = :de
=> :de
irb(main):002:0> question = Question.new
=> #<Question id: nil, created_at: nil, updated_at: nil>
irb(main):003:0> question.text = "Event"
=> "Event"
irb(main):004:0> I18n.locale = :fr
=> :fr
irb(main):005:0> question.text = "événement"
=> "événement"
irb(main):006:0> question.text
=> "événement"
irb(main):007:0> question.text_fr
=> "événement"
irb(main):008:0> question
=> #<Question id: nil, created_at: nil, updated_at: nil>
```

I'm using the Table backend here, but that shouldn't matter and just to be sure I tried with json and got the same result.

**Comment by shioyama** [comment] 2018-08-28 13:10
Do you have any other special configuration? That might explain it.

**Comment by enthusiasmus** [comment] 2018-08-28 13:56
Our `config/initializers/mobility.rb` contains only 
```
Mobility.configure do |config|
  config.default_backend = :json
  config.accessor_method = :translates
  config.query_method    = :i18n
end
```
So i don't think there is any other special configuration. But anyway... Let's start debugging! :-)
Thanks for the very fast response!

**Comment by shioyama** [comment] 2018-08-28 14:17
Hmm strange.

Well, if you can create a clean app that demonstrates the problem, then I can try to help. I have a hard time seeing how this would happen though since the fallbacks plugin just cycles through fallbacks, nothing special.

**Comment by shioyama** [comment] 2018-08-29 08:58
I am going to close this issue since I cannot reproduce it. Feel free to re-open if/when you have some public code which can reproduce it.

**Closed by shioyama** 2018-08-29 08:58 UTC

**Comment by enthusiasmus** [comment] 2018-08-29 13:44
After some hours of debugging we find out, that we are overwriting `def [](locale)` of the I18n::Locale::Fallbacks class. So its definitely no bug. Thanks for your time and fast response as always! :+1:

**Comment by shioyama** [comment] 2018-08-29 15:01
Great to hear you figured out the issue!
