### ISSUE TITLE
Uniqueness validator returns exists for non existing records

### ISSUE THREAD

**Issue by jonian** [shioyama/mobility#33] opened 2017-05-24 10:16 UTC
Hi, thank you for this great gem.

When I use `uniqueness: true` in validations, I get the following message. I have tried using it with an existing database and a new database.

    Running via Spring preloader in process 16712
    Loading development environment (Rails 5.1.1)
    [1] pry(main)> Category.create(name: 'CSR')
       (0.2ms)  BEGIN
      Mobility::ActiveRecord::StringTranslation Exists (1.3ms)  SELECT  1 AS one FROM "mobility_string_translations" WHERE "mobility_string_translations"."key" = $1 AND "mobility_string_translations"."translatable_id" IS NULL AND "mobility_string_translations"."translatable_type" = $2 AND "mobility_string_translations"."locale" = $3 LIMIT $4  [["key", "name"], ["translatable_type", "Category"], ["locale", "en"], ["LIMIT", 1]]
       (0.2ms)  ROLLBACK
    ActiveRecord::ImmutableRelation: ActiveRecord::ImmutableRelation
    from /home/jonian/.gem/ruby/2.4.0/gems/activerecord-5.1.1/lib/active_record/relation/query_methods.rb:936:in `assert_mutability!'

I am using the `Key-Store` backend, `PostgreSQL 9.6.3`, `Rails 5.1.1` and `Ruby 2.4.1`.
The model configuration is below:

    class Category < ApplicationRecord
      # Include modules
      include Mobility

      # Translate attributes
      translates :name, type: :string, locale_accessors: true, fallbacks: true

      # Attribute validations
      validates :name, presence: true, uniqueness: true
    end

    class ApplicationRecord < ActiveRecord::Base
      # Set class as abstract
      self.abstract_class = true
    end

**Comment by jonian** [comment] 2017-05-24 15:21
It seems that the problem is in `mobility/lib/mobility/active_record/uniqueness_validator.rb` line `14`.

    if relation.exists?
      error_options = options.except(:case_sensitive, :scope, :conditions)
      error_options[:value] = value

      record.errors.add(attribute, :taken, error_options)
    end

Using `relation.exists?` or `relation.any?` I get the same error. If i use `relation.present?`, it works as expected.

**Comment by shioyama** [comment] 2017-05-27 13:06
Ok I found the root cause.

For the record, it's [this line](https://github.com/shioyama/mobility/blob/766d958b2c0a2260e017be04029a3606aa6b0521/lib/mobility/backend/active_record/query_methods.rb#L23), which checks if the relation responds to a method (`mobility_where_chain`). Calling `respond_to?`, which should be fine, actually [memoizes an arel object here](https://github.com/shioyama/rails/blob/c48b21685f4fec1c7a1c9b4e0dde4da89140ee22/activerecord/lib/active_record/relation/delegation.rb#L116) in AR. This in turn is picked up by `assert_mutability!` [here](https://github.com/shioyama/rails/blob/c48b21685f4fec1c7a1c9b4e0dde4da89140ee22/activerecord/lib/active_record/relation/query_methods.rb#L936), which is what's raising the error.

I can fix this by replacing `relation.respond_to?` by `relation.singleton_class.methods.include?`, which seems ugly but works. This feels like an AR bug but I don't know the internals of what must have changed, so not quite sure...

Anyway that change should be relatively harmless and fix the issue in Rails 5.1. :smile:

**Comment by shioyama** [comment] 2017-05-28 00:09
This should be fixed now on master, please give it a try.

**Closed** 2017-05-28 00:09 UTC
Labels: active_record, active_record_5.1

**Comment by jonian** [comment] 2017-05-28 17:53
@shioyama I confirm that this is working without issues now. Thank you for the quick fix.
