### ISSUE TITLE
Could not find generator mobility:install

### ISSUE THREAD

**Issue by wenderjean** [shioyama/mobility#272] opened 2018-09-14 21:59 UTC
## Context
So, I'm trying to use mobility#0.8.0 in my rails application but I can't use generators, rails generator says it doesn't exist.

```bash
$ rails generate mobility:install
Running via Spring preloader in process 95848
Could not find generator 'mobility:install'. Maybe you meant 'pundit:install', 'bullet:install' or 'devise:install'
Run `rails generate --help` for more options.
```
```ruby
source 'https://rubygems.org'

ruby '2.4.4'

gem 'mobility', '~> 0.8.0'`
gem 'rails', '~> 5.2.0'
```

```bash
Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64 x86_64
```

**Comment by shioyama** [comment] 2018-09-14 22:56
I'm finding this happens in combination with MobilityRansack, maybe something about loading constants... very strange.

**Comment by shioyama** [comment] 2018-09-14 23:57
I created a clean Rails 5.2.0 app, added mobility 0.8.0 to the gemfile and ran `bundle exec rails g mobility:install` and it ran fine.

So there is something particular that triggers this issue. I also observed it locally in combination with MobilityRansack, so I suspect it has something to do with load order.

**Comment by shioyama** [comment] 2018-09-15 01:42
I can no longer reproduce this, however much I mess with my Gemfile.

One thing is to remember to always `bundle exec spring stop` when changing any gem versions, etc. in your Gemfile, since otherwise Spring will use the original version. This makes it actually hard to figure out what's going on here.

In any case, if you can give me a reproducible case to debug, I can try to solve this, but otherwise it's really impossible to fix.

**Comment by shioyama** [comment] 2018-09-15 08:09
So actually, I went through my command log and I had mistyped `bundle exec rails mobility:install`, forgetting the `generate`, which was why at one point I was getting an error.

So I am actually completely unable to reproduce this, and have never seen it or heard about it affecting anybody else. Also, the generator code has not changed for a long long time. So I'm going to close this, but if you do have an app or example which reproduces it, please post and re-open.

**Closed by shioyama** 2018-09-15 08:09 UTC
Labels: active_record, bug, rails

**Comment by wenderjean** [comment] 2018-09-17 01:39
Thank you for answers @shioyama I was fighting some environment issue, right after I read your answers I've tried to reproduce the problem in another environment and it works fine.
